/**
 * Whole screens, for looking at rather than for reading about.
 *
 * Three products, drawn from what each one actually wears:
 *
 *   - **Airwave Hub** and **Airwave Companion** are the Airwave windows. Their frames hold the
 *     design's generated stylesheets and each product's own `styles.css`, AquaArt's drawings, and the
 *     products' own window kits and icons — see `./airwave-screens.tsx`.
 *   - **Airwave**, the player, is served as a shell generated from
 *     `design/frontends/airwave-now-playing.html` (design/decisions.md DEC-019). That shell is one
 *     large document with its own scripts and cannot be portalled into a frame, so the player's
 *     screens here are the component library's page skin — the React interface in
 *     `music-player/src`, which shares the shell's look and is kept but no longer served. The frames
 *     say so on screen.
 *
 * How much of each screen is the product's own varies, and each screen's note says which:
 *
 *   - **The product's own view** (`./view-specimens.tsx`): the hub sections Groups, Library, Live TV,
 *     Profiles, Shared links, Recommendations, Discord, Network, Backup and Diagnostics, and the
 *     companion's Settings, Backup and About. The view component runs as it does in the app, with a
 *     recording of a real hub or companion where its server would be (DEC-030).
 *   - **Arranged here from the kit** (`./airwave-screens.tsx`): the hub's sign-in, first run,
 *     Overview, Providers, Downloads and confirmation sheet, and the companion's Library, Live TV,
 *     Remote and confirmation sheet. Those panes need states a recording cannot reach — a refused
 *     link, a failed download, a sheet already open — so the arrangement and the words are taken
 *     from the views and the data is fixture data (DEC-009).
 *   - **The player** is the component library's page skin here; the served shell itself is shown as
 *     screenshots under The served shell, regenerated by `scripts/styleguide-shell-shots.mjs`.
 */
import { useState, type ReactNode } from 'react';
import { BRANDING } from '@now-playing/contracts';
import { AquaTable, Button, Checkbox, KeyValueList, Panel, PanelSection, SegmentedControl, SourceBadge, StatusDot, TextField, type ColumnDef } from '../src/index.js';
import { PageDemo } from '../gallery/specimens.js';
import { CONSTELLATION_ALBUMS, ConstellationField, SpectrumSpecimen, type FixtureAlbum } from './visualisers.js';
import {
  COMPANION_CSS,
  CompanionConfirmScreen,
  CompanionLibraryScreen,
  CompanionLiveTvScreen,
  CompanionRemoteScreen,
  HUB_CSS,
  HubConfirmScreen,
  HubDownloadsScreen,
  HubFirstRunScreen,
  HubOverviewScreen,
  HubProvidersScreen,
  HubSignInScreen,
  prepareAirwaveDocument,
} from './airwave-screens.js';
import {
  CompanionAboutScreen,
  CompanionBackupScreen,
  CompanionSettingsView,
  HubBackupScreen,
  HubDiagnosticsScreen,
  HubDiscordScreen,
  HubGroupsScreen,
  HubLibraryScreen,
  HubLiveTvScreen,
  HubNetworkScreen,
  HubProfilesScreen,
  HubRecommendationsScreen,
  HubSharesScreen,
} from './view-specimens.js';
/*
 * The player's own stylesheet, as a string rather than as a page style.
 *
 * It carries the rules a component library cannot: what `body` looks like, how the app fills the
 * window, and the product-specific classes the real views use. Imported here so a frame can put it
 * inside itself, where it belongs — loading it onto the styleguide's own page would give the page
 * the player's background. The hub's and the companion's are assembled in ./airwave-screens.tsx.
 */
import playerCss from '../../../music-player/src/styles.css?inline';

export type ProductId = 'player' | 'hub' | 'companion';

export const PRODUCT_CSS: Readonly<Record<ProductId, string>> = { player: playerCss, hub: HUB_CSS, companion: COMPANION_CSS };

export interface Screen {
  id: string;
  product: ProductId;
  label: string;
  /** What this screen is for, and what to look at when you resize it. */
  note: string;
  render: () => ReactNode;
}

export interface ProductSpec {
  id: ProductId;
  label: string;
  skin: string;
  note: string;
  /**
   * True for the Airwave windows: the frame holds only the product's own stylesheets (none of the
   * component library's), and AquaArt is installed in it before anything is drawn.
   */
  isolated: boolean;
  prepare?: (doc: Document) => void;
  /** The sizes this product is really seen at, smallest first; the first two are shown to begin with and in print. */
  devices: readonly string[];
  shown: readonly [string, string];
  /**
   * Whether the 44px touch-target and 12px touch-text floors are held. The page skin has a touch
   * layer and is held to them. The Airwave windows keep the design's desktop density at every
   * pointer, so their sizes are measured and printed but not failed (design/decisions.md DEC-027).
   */
  touchFloors: boolean;
}

export const PRODUCTS: readonly ProductSpec[] = [
  {
    id: 'player',
    label: BRANDING.products.player,
    skin: 'Page skin (component library)',
    note: 'The player. These screens are the library’s page skin — the React interface kept in music-player/src. The served player is the shell generated from design/frontends/airwave-now-playing.html, which has the same look, is photographed under The served shell and is recorded surface by surface under Every screen.',
    isolated: false,
    devices: ['small-phone', 'phone', 'tablet', 'laptop', 'desktop'],
    shown: ['phone', 'laptop'],
    touchFloors: true,
  },
  {
    id: 'hub',
    label: BRANDING.products.hub,
    skin: 'Airwave window',
    note: 'Served by the container on port 4546 and opened in a browser — often, in practice, on a phone. Below 640px the tools scroll sideways, tiles go two-up and tables drop their secondary columns.',
    isolated: true,
    prepare: prepareAirwaveDocument,
    devices: ['small-phone', 'phone', 'tablet', 'laptop', 'desktop'],
    shown: ['phone', 'laptop'],
    touchFloors: false,
  },
  {
    id: 'companion',
    label: BRANDING.products.companion,
    skin: 'Airwave window',
    note: 'An Electron window on Windows: 640 × 760 as it opens, never smaller than 520 × 440. Its chrome is its title bar; Windows draws minimise, maximise and close over the top-right corner, which a frame on a page cannot show.',
    isolated: true,
    prepare: prepareAirwaveDocument,
    devices: ['window-min', 'window', 'laptop'],
    shown: ['window-min', 'window'],
    touchFloors: false,
  },
];

/* ---------------------------------------------------------------- player */

function PlayerSettings() {
  const [crossfade, setCrossfade] = useState(true);
  const [gapless, setGapless] = useState(true);
  return (
    <div className="np-app sg-screen-page">
      <div className="np-body">
        <div className="np-body__inner">
          <div className="np-section-head">
            <h2>Settings</h2>
            <p>What this app can do here, and what it cannot — with the reason in each case.</p>
          </div>
          <Panel title="Playback">
            <PanelSection>
              <Checkbox checked={crossfade} onChange={(event) => setCrossfade(event.currentTarget.checked)}>
                Crossfade songs
              </Checkbox>
              <Checkbox checked={gapless} onChange={(event) => setGapless(event.currentTarget.checked)}>
                Keep songs from the same album gapless
              </Checkbox>
            </PanelSection>
          </Panel>
          <Panel title="Platforms">
            <PanelSection>
              <p className="sg-note">Three questions, because the platforms answer them differently. Every “no” says whose rule it is.</p>
              <ul className="sg-platforms">
                {[
                  { id: 'local', name: 'This device', play: 'Yes', keep: 'Yes', save: 'Yes', tone: 'ok' as const },
                  { id: 'bandcamp', name: 'Bandcamp', play: 'No', keep: 'Sometimes', save: 'Sometimes', tone: 'warning' as const },
                  { id: 'youtube', name: 'YouTube', play: 'Sometimes', keep: 'No', save: 'No', tone: 'neutral' as const },
                  { id: 'spotify', name: 'Spotify', play: 'Sometimes', keep: 'No', save: 'No', tone: 'neutral' as const },
                ].map((row) => (
                  <li key={row.id}>
                    <span className="sg-platforms__head">
                      <SourceBadge provider={row.id} />
                      <strong>{row.name}</strong>
                    </span>
                    <span className="sg-platforms__routes">
                      <StatusDot kind={row.tone} label={`Play here: ${row.play}`} />
                      <StatusDot kind={row.tone} label={`Keep offline: ${row.keep}`} />
                      <StatusDot kind={row.tone} label={`Save a file: ${row.save}`} />
                    </span>
                  </li>
                ))}
              </ul>
            </PanelSection>
          </Panel>
          <Panel title="Hub">
            <PanelSection>
              <TextField label="Hub address" value="https://living-room.local:4546" onChange={() => undefined} />
              <div className="sg-row">
                <Button variant="default">Pair</Button>
                <Button>Forget</Button>
              </div>
            </PanelSection>
          </Panel>
        </div>
      </div>
    </div>
  );
}

/* --------------------------------------------------------------- screens */

export const SCREENS: readonly Screen[] = [
  {
    id: 'player-now-playing',
    product: 'player',
    label: 'Now playing and library',
    note: 'The whole page skin at once. Narrow it and watch the list drop its number and artist columns and put the artist under the title instead.',
    render: () => <PageDemo />,
  },
  {
    id: 'player-settings',
    product: 'player',
    label: 'Settings',
    note: 'Where most of the app’s explaining happens, so it is the screen where text size and wrapping matter most.',
    render: () => <PlayerSettings />,
  },
  {
    id: 'player-engine',
    product: 'player',
    label: 'Now playing (audio chain)',
    note: 'What the audio chain is doing to the song, and the spectrum visualiser under it — drawn by the player’s own spectrum code from a generated analyser frame.',
    render: () => <EngineScreen />,
  },
  {
    id: 'player-constellation',
    product: 'player',
    label: 'Constellation',
    note: 'The library as a star field, placed by the player’s own layout code. The table beside it is the same information, not a fallback.',
    render: () => <ConstellationScreen />,
  },
  {
    id: 'hub-sign-in',
    product: 'hub',
    label: 'Sign in',
    note: 'Not signed in: the same window with every tab locked and the form in the pane. There is no separate sign-in page.',
    render: () => <HubSignInScreen />,
  },
  {
    id: 'hub-first-run',
    product: 'hub',
    label: 'First run',
    note: 'Signed in with the first-run password: the amber gate on Overview, the other five tabs locked. The tiles that depend on gated routes say they are off instead of showing a number.',
    render: () => <HubFirstRunScreen />,
  },
  {
    id: 'hub-overview',
    product: 'hub',
    label: 'Overview',
    note: 'Six tiles, what needs attention, each provider’s health as a word, and the hub’s own facts. Below 640px the tiles go two-up and the key–value list stacks.',
    render: () => <HubOverviewScreen />,
  },
  {
    id: 'hub-providers',
    product: 'hub',
    label: 'Music ▸ Providers',
    note: 'A table inside a well. Below 640px the Role column and the two request counters are dropped rather than scrolled sideways.',
    render: () => <HubProvidersScreen />,
  },
  {
    id: 'hub-downloads',
    product: 'hub',
    label: 'Music ▸ Downloads',
    note: 'Every state a job can be in, as words or a bar; the formats this hub can write, struck through where it cannot; and the storage line.',
    render: () => <HubDownloadsScreen />,
  },
  {
    id: 'hub-groups',
    product: 'hub',
    label: 'Groups',
    note: 'The hub’s own Groups view, answered by a recorded hub: two groups, nothing playing, and the New Group row. Open one to see its transport, queue and invites.',
    render: () => <HubGroupsScreen />,
  },
  {
    id: 'hub-library',
    product: 'hub',
    label: 'Music ▸ Library',
    note: 'The hub’s own Library view: two folders in the data volume, each with its own Scan (that folder alone) and Remove, the fields to add a folder beside Scan Now, and the songs found.',
    render: () => <HubLibraryScreen />,
  },
  {
    id: 'hub-live-tv',
    product: 'hub',
    label: 'Music ▸ Live TV from the companion',
    note: 'The hub’s own Live TV row, read-only: what a sharing companion sent, or — as recorded here — the sentence saying nothing has arrived yet. Channels are added and removed in the companion.',
    render: () => <HubLiveTvScreen />,
  },
  {
    id: 'hub-recommendations',
    product: 'hub',
    label: 'Music ▸ Recommendations',
    note: 'The hub’s own Recommendations view: the defaults every player’s engine starts from, with Save and Revert for the whole form.',
    render: () => <HubRecommendationsScreen />,
  },
  {
    id: 'hub-profiles',
    product: 'hub',
    label: 'Devices ▸ Profiles',
    note: 'The hub’s own Profiles view on a hub with no paired players yet: the empty list says what fills it.',
    render: () => <HubProfilesScreen />,
  },
  {
    id: 'hub-shares',
    product: 'hub',
    label: 'Sharing ▸ Shared links',
    note: 'The hub’s own Shared links view: one album link with its expiry and counts, and Create Link with the picker of hub playlists and albums and how long the link lasts.',
    render: () => <HubSharesScreen />,
  },
  {
    id: 'hub-discord',
    product: 'hub',
    label: 'Sharing ▸ Discord',
    note: 'The hub’s own Discord view with no bot token yet: the form, Save and Start with Revert, and Invite the Bot disabled with its reason until a token is saved.',
    render: () => <HubDiscordScreen />,
  },
  {
    id: 'hub-network',
    product: 'hub',
    label: 'System ▸ Network',
    note: 'The hub’s own Network view: how it listens and where it is reached from, with an explicit Save and Revert — nothing applies as you type.',
    render: () => <HubNetworkScreen />,
  },
  {
    id: 'hub-backup',
    product: 'hub',
    label: 'System ▸ Backup',
    note: 'The hub’s own Backup view: one archive with its own Download, the space it has, and the settings — where, what goes in, the daily schedule and how many to keep.',
    render: () => <HubBackupScreen />,
  },
  {
    id: 'hub-diagnostics',
    product: 'hub',
    label: 'System ▸ Diagnostics',
    note: 'The hub’s own Diagnostics view: the recent log at a chosen level and the support bundle, which says what it leaves out.',
    render: () => <HubDiagnosticsScreen />,
  },
  {
    id: 'hub-confirm-sheet',
    product: 'hub',
    label: 'Confirmation sheet',
    note: 'A destructive action asks in a sheet that drops over the pane. Cancel has the focus, Escape cancels, and the window behind it is inert. This is the hub kit’s own sheet, asked for real.',
    render: () => <HubConfirmScreen />,
  },
  {
    id: 'companion-folders',
    product: 'companion',
    label: 'Library',
    note: 'Saved Music, Saved TV and Saved Movies, then the songs found. A folder whose drive is away is said so in its row and under the list.',
    render: () => <CompanionLibraryScreen />,
  },
  {
    id: 'companion-live-tv',
    product: 'companion',
    label: 'Live TV',
    note: 'A kept link, one that stopped answering (Check Again), one being checked, and a refused one: the reason under the field, the typed text left in it.',
    render: () => <CompanionLiveTvScreen />,
  },
  {
    id: 'companion-transfers',
    product: 'companion',
    label: 'Remote',
    note: 'Pairing a device, the hub connection and what is shared, and transfers. Untick sharing and Sync Now is disabled with its reason.',
    render: () => <CompanionRemoteScreen />,
  },
  {
    id: 'companion-settings',
    product: 'companion',
    label: 'Settings',
    note: 'The companion’s own Settings view, answered by a recorded companion: one downloader ready, one still being set up (a bar, and the badge on the tool), FFmpeg found on the PATH; then General with update checks and notifications, Downloads, and Network with the helper on this PC only.',
    render: () => <CompanionSettingsView />,
  },
  {
    id: 'companion-backup',
    product: 'companion',
    label: 'Settings ▸ Backup',
    note: 'The companion’s own Backup view, recorded on a new install: a weekly schedule, five kept, what goes in (recommendation settings only once a hub is paired), and Back Up Now waiting for a folder to be chosen.',
    render: () => <CompanionBackupScreen />,
  },
  {
    id: 'companion-about',
    product: 'companion',
    label: 'Settings ▸ Storage and About',
    note: 'The companion’s own About view: where its data lives, the cache and logs with their controls, and the build, with how updates are checked. The paths are the installed ones.',
    render: () => <CompanionAboutScreen />,
  },
  {
    id: 'companion-confirm-sheet',
    product: 'companion',
    label: 'Confirmation sheet',
    note: 'The companion’s sheet is a modal dialog. For a destructive action Cancel is the default button, so Return never removes anything. This is the companion kit’s own sheet, asked for real.',
    render: () => <CompanionConfirmScreen />,
  },
];

/* ------------------------------------------------------------ visualisers */

/**
 * The Constellation section. The field is `ConstellationField` from ./visualisers.tsx, which places
 * every star with the player's own `layoutStars`; only the renderer differs (SVG in a frame, WebGL
 * in the app), which is the boundary DEC-009 draws for every mockup.
 */
function ConstellationScreen() {
  const [mode, setMode] = useState<'stars' | 'table'>('stars');
  const [selected, setSelected] = useState<FixtureAlbum | undefined>(CONSTELLATION_ALBUMS[2]);
  const artists = new Set(CONSTELLATION_ALBUMS.map((a) => a.artist)).size;
  return (
    <div className="np-app sg-screen-page">
      <div className="np-body">
        <div className="np-body__inner">
          <div className="np-section-head">
            <h2>Constellation</h2>
            <p>Every album is a star, grouped by artist. Pick one to play it.</p>
          </div>
          <Panel title="Constellation">
            <PanelSection>
              <div className="player-toolbar-row">
                <SegmentedControl
                  label="View"
                  value={mode}
                  onChange={setMode}
                  segments={[
                    { value: 'stars', label: 'Stars' },
                    { value: 'table', label: 'Table' },
                  ]}
                />
                <span className="player-hint">
                  {CONSTELLATION_ALBUMS.length} albums from {artists} artists. Both views show the same thing; the table is not a fallback.
                </span>
              </div>
            </PanelSection>
            {mode === 'stars' ? (
              <ConstellationField selected={selected?.album} onSelect={setSelected} />
            ) : (
              <AquaTable
                variant="page"
                label="Albums"
                rowKey={(row: FixtureAlbum) => row.album}
                rows={[...CONSTELLATION_ALBUMS]}
                columns={
                  [
                    { id: 'album', header: 'Album', primary: true, cell: (row) => row.album, stackText: (row) => row.artist },
                    { id: 'artist', header: 'Artist', cell: (row) => row.artist },
                    { id: 'tracks', header: 'Songs', align: 'right', width: 56, cell: (row) => row.trackCount },
                  ] as ColumnDef<FixtureAlbum>[]
                }
              />
            )}
            {selected ? (
              <PanelSection title={`${selected.album} — ${selected.artist}`}>
                <div className="player-toolbar-row">
                  <Button size="small" icon="play">
                    Play album
                  </Button>
                  <span className="player-hint">{selected.trackCount} songs</span>
                </div>
              </PanelSection>
            ) : null}
          </Panel>
        </div>
      </div>
    </div>
  );
}

/**
 * The Now playing section: what the audio chain is doing to the song, with the spectrum under it.
 * The rows are `NowPlaying.tsx`'s own keys with fixture values; the spectrum is `SpectrumSpecimen`.
 */
function EngineScreen() {
  return (
    <div className="np-app sg-screen-page">
      <div className="np-body">
        <div className="np-body__inner">
          <div className="np-section-head">
            <h2>Now playing</h2>
            <p>What the audio chain is doing to this song, measured rather than assumed.</p>
          </div>
          <Panel title="How this is being played">
            <PanelSection>
              <KeyValueList
                items={[
                  { key: 'Song', value: 'Midnight Set, Side B — Fennel Grove' },
                  { key: 'Position', value: '0:23 of 2:58' },
                  { key: 'Source', value: 'A file on this device' },
                  { key: 'Equalizer', value: 'Bass Lift — the preset chosen for this album' },
                  { key: 'Limiter', value: 'On — prevents clipping when the equalizer adds gain' },
                  { key: 'Headroom', value: '3.0 dB trim applied to keep the boosted signal below full scale' },
                  { key: 'Retuning', value: 'Off — playing at the original pitch' },
                  { key: 'Added latency', value: '11.6 ms' },
                ]}
              />
              <SpectrumSpecimen />
            </PanelSection>
          </Panel>
        </div>
      </div>
    </div>
  );
}
