/**
 * `pnpm mockups:build [player|hub|companion …] [--out <dir>]`
 *
 * Renders the living mockups — design/frontends/airwave-now-playing.html, airwave-hub.html and
 * airwave-companion.html — from the apps as they are now: each app is built from its sources, run in
 * Chrome on sample data, walked through its screens and states, and each state is written out as
 * readable markup beside the app's own stylesheets (design/decisions.md DEC-038). Same sources, same
 * bytes. `--out` writes somewhere else (the up-to-date gate and `pnpm mockups:diff` use a scratch
 * folder); without it the committed mockups are rewritten.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { launch, removeDir, ROOT } from './lib/browser.mjs';
import { writeMockup } from './lib/document.mjs';
import { inputsHash } from './lib/inputs.mjs';
import { keepUnchangedPictures } from './lib/pictures.mjs';
import { renderApp } from './lib/session.mjs';
import player from './apps/player.mjs';
import hub from './apps/hub.mjs';
import companion from './apps/companion.mjs';

export const APPS = { player, hub, companion };
export const MOCKUP_DIR = 'design/frontends';

/**
 * Time-based ids (UUIDv7: milliseconds, then random bits) an app makes while the walk-through runs
 * depend on exactly when a step landed. Each is written as a stable id instead — the same one
 * everywhere it appears, numbered in the order the file first mentions it.
 */
export function stableIds(html) {
  const seen = new Map();
  return html.replace(/\b[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/g, (id) => {
    if (!seen.has(id)) seen.set(id, `00000000-0000-7000-8000-${String(seen.size + 1).padStart(12, '0')}`);
    return seen.get(id);
  });
}

/** Words wrapped to lines of at most `width`, each indented by `indent`. */
function wrap(text, width = 98, indent = '  ') {
  const lines = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    if (line && indent.length + line.length + 1 + word.length > width) {
      lines.push(indent + line);
      line = word;
    } else line = line ? `${line} ${word}` : word;
  }
  if (line) lines.push(indent + line);
  return lines.join('\n');
}

export function banner(app) {
  return `  ${app.title} — the living mockup.

${wrap(`GENERATED by \`pnpm mockups:build\` (scripts/mockups/) from the app itself: ${app.from}`)}

  Every state below is the real app's markup as it drew it on sample data, beside the app's own
  stylesheets (each <style data-mock-source> is a verbatim copy of the file it names). Open this
  file straight from disk; it runs none of the app's code and makes no network request. The panel
  in the bottom-right corner lists every state; clicks on tabs, menus and buttons follow the app.

  Edit it freely — markup, words, CSS. To carry your edits into the app, ask Claude to
  "incorporate my mockup changes": it runs \`pnpm mockups:diff ${app.id}\`, makes each change in the
  app's real sources (AGENTS.md, "Living mockups"), and regenerates this file. Regenerating
  without doing that replaces your edits, so keep a copy (\`pnpm mockups:export <folder>\`).

  The hand-drawn design this app started from is design/frontends/origin/${app.file} (frozen).`;
}

/** Render the named apps into `outDir`. Returns per-app results; throws on the first failure. */
export async function buildMockups(names, outDir) {
  const browser = await launch();
  const results = [];
  try {
    for (const name of names) {
      const app = APPS[name];
      if (!app) throw new Error(`no mockup called ${name} (player, hub or companion)`);
      console.info(`${app.id}: building the app`);
      const prepared = await app.prepare();
      try {
        console.info(`${app.id}: rendering`);
        const { states, errors, unanswered } = await renderApp(browser, app, prepared);
        const unexpected = unanswered.filter((request) => !(app.unanswered ?? []).some((pattern) => pattern.test(request)));
        if (unexpected.length) throw new Error(`${app.id}: the app asked for things the sample data does not answer:\n  ${unexpected.join('\n  ')}\nAdd them to the fixtures (scripts/mockups/fixtures) or, if they are meant to fail, to the app's unanswered list.`);
        const unwanted = errors.filter((error) => !(app.expectedErrors ?? []).some((pattern) => pattern.test(error)));
        if (unwanted.length) throw new Error(`${app.id}: the app reported errors while rendering:\n  ${[...new Set(unwanted)].join('\n  ')}`);
        // Canvas pictures that match the committed ones to within rendering noise keep their bytes.
        const committed = join(ROOT, MOCKUP_DIR, app.file);
        await keepUnchangedPictures(browser, existsSync(committed) ? readFileSync(committed, 'utf8') : null, states);
        const stylesheets = app.stylesheets(states);
        let html = writeMockup({
          app: app.id,
          title: `${app.title} — mockup`,
          banner: banner(app),
          inputs: inputsHash(ROOT, app.inputs),
          stylesheets,
          states,
        });
        if (app.stableIds) html = stableIds(html);
        const file = join(outDir, app.file);
        mkdirSync(outDir, { recursive: true });
        writeFileSync(file, html);
        results.push({ app: app.id, file, bytes: Buffer.byteLength(html), states: states.length });
        console.info(`${app.id}: ${states.length} states, ${Math.round(Buffer.byteLength(html) / 1024)} KB → ${file}`);
      } finally {
        removeDir(prepared.dist);
      }
    }
  } finally {
    await browser.close();
  }
  return results;
}

export async function main(argv) {
  const at = argv.indexOf('--out');
  const outDir = resolve(ROOT, at >= 0 ? argv[at + 1] : MOCKUP_DIR);
  const names = argv.filter((arg, i) => !arg.startsWith('--') && argv[i - 1] !== '--out');
  await buildMockups(names.length ? names : Object.keys(APPS), outDir);
}
