"""
Build the Airwave window stylesheets from the two window designs.

design/frontends/origin/airwave-companion.html and airwave-hub.html are where the companion's and
the hub's window kit came from, exactly as airwave-now-playing.html is for the player (see
music-player/scripts/make-shell.py). They are frozen (DEC-038): a change to the kit is an asserted
entry in EDITS below. Their <style> blocks are one kit drawn twice: the companion's
is the base, the hub's adds tiles, tables, capability chips and the first-run gate. This script
copies them out verbatim, so the products cannot drift from the designs by hand:

  packages/aqua-ui/src/styles/airwave-window.css   the companion's sheet, whole
  packages/aqua-ui/src/styles/airwave-hub.css      every hub rule the base does not already carry

Run:  python packages/aqua-ui/scripts/make-window-css.py     (pnpm build:window-css)
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
FRONTENDS = ROOT / 'design' / 'frontends' / 'origin'
OUT = ROOT / 'packages' / 'aqua-ui' / 'src' / 'styles'


def style_of(name: str) -> str:
    html = (FRONTENDS / name).read_text(encoding='utf-8')
    found = re.findall(r'<style>(.*?)</style>', html, re.S)
    assert len(found) == 1, f'{name}: expected one <style>, found {len(found)}'
    return found[0].strip('\n') + '\n'


def chunks(css: str) -> list[str]:
    """Top-level rules (and at-rules), each with the comment that introduces it."""
    out, depth, start, i, n = [], 0, 0, 0, len(css)
    while i < n:
        if css.startswith('/*', i):
            i = css.index('*/', i) + 2
            continue
        ch = css[i]
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                out.append(css[start:i + 1])
                start = i + 1
        i += 1
    assert depth == 0, 'unbalanced braces'
    tail = css[start:].strip()
    assert not tail or tail.startswith('/*'), f'unparsed tail: {tail[:60]!r}'
    return out


def norm(rule: str) -> str:
    return re.sub(r'\s+', ' ', re.sub(r'/\*.*?\*/', '', rule, flags=re.S)).strip()


companion = style_of('airwave-companion.html')
hub = style_of('airwave-hub.html')
base = {norm(r) for r in chunks(companion)}
extra = [r for r in chunks(hub) if norm(r) not in base]
assert len(extra) > 20, 'the hub design should add tiles, tables and the gate'

# The designs are frozen history (design/decisions.md DEC-038): a change to the window kit is made
# here, as an edit to what was copied out, asserted against the exact text it replaces so a drift
# is a loud failure, the way music-player/scripts/make-shell.py records the player's.
# Each entry is (output file, old text, new text). None yet: both sheets are the designs' own.
EDITS: list[tuple[str, str, str]] = []


def edited(name: str, css: str) -> str:
    for target, old, new in EDITS:
        if target != name:
            continue
        n = css.count(old)
        assert n == 1, f'{name}: expected one occurrence, found {n}: {old[:80]!r}'
        css = css.replace(old, new)
    return css


HEAD = ('/* GENERATED by packages/aqua-ui/scripts/make-window-css.py from design/frontends/origin/{src}.\n'
        '   Do not edit: the design is frozen (DEC-038); record a change in EDITS there and run `pnpm build:window-css`. */\n')
(OUT / 'airwave-window.css').write_text(HEAD.format(src='airwave-companion.html') + edited('airwave-window.css', companion), encoding='utf-8', newline='\n')
(OUT / 'airwave-hub.css').write_text(HEAD.format(src='airwave-hub.html') + edited('airwave-hub.css', ''.join(extra).lstrip('\n') + '\n'), encoding='utf-8', newline='\n')
sys.stdout.write(f'airwave-window.css: {len(chunks(companion))} rules; airwave-hub.css: {len(extra)} rules\n')
