#!/usr/bin/env node
/** Generates LICENSES.md from the installed production dependencies of every workspace package. */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const workspaces = ['packages/contracts', 'packages/domain', 'packages/aqua-ui', 'packages/audio-core', 'packages/recommendations', 'music-player', 'docker-container', 'windows-companion'];
const seen = new Map();
function visit(name, from) {
  if (seen.has(name) || name.startsWith('@now-playing/')) return;
  const dir = join(root, 'node_modules', name);
  const pj = join(dir, 'package.json');
  if (!existsSync(pj)) {
    seen.set(name, { version: '?', license: 'unresolved', from });
    return;
  }
  const pkg = JSON.parse(readFileSync(pj, 'utf8'));
  const license = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? (Array.isArray(pkg.licenses) ? pkg.licenses.map((l) => l.type).join(' OR ') : 'UNKNOWN');
  seen.set(name, { version: pkg.version, license, from });
  for (const dep of Object.keys(pkg.dependencies ?? {})) visit(dep, name);
}
for (const ws of workspaces) {
  const pkg = JSON.parse(readFileSync(join(root, ws, 'package.json'), 'utf8'));
  for (const dep of Object.keys(pkg.dependencies ?? {})) visit(dep, ws);
}
const rows = [...seen.entries()].sort(([a], [b]) => a.localeCompare(b));
const counts = {};
for (const [, v] of rows) counts[v.license] = (counts[v.license] ?? 0) + 1;
const disallowed = rows.filter(([, v]) => /GPL(?!-.*with)|SSPL|CC-BY-NC/i.test(v.license) && !/LGPL/.test(v.license));
let md = `# Third-party licenses\n\nGenerated by \`node scripts/licenses.mjs\` from the installed production dependency graph of every workspace package (${rows.length} packages). The suite itself is MIT.\n\n## Summary\n\n| License | Packages |\n|---|---:|\n`;
for (const [l, n] of Object.entries(counts).sort((a, b) => b[1] - a[1])) md += `| ${l} | ${n} |\n`;
md += `\n${disallowed.length ? `**Attention:** ${disallowed.length} package(s) carry copyleft/non-commercial licenses: ${disallowed.map(([n]) => n).join(', ')}` : 'No GPL/SSPL/non-commercial licenses are present in the production graph.'}\n\n## Packages\n\n| Package | Version | License | Pulled in by |\n|---|---|---|---|\n`;
for (const [name, v] of rows) md += `| ${name} | ${v.version} | ${v.license} | ${v.from} |\n`;
md += `\n## Bundled runtime notes\n\n- Docker image: Debian packages incl. FFmpeg (GPL/LGPL, invoked as a separate process, not linked).\n- Electron: MIT; Chromium/Node components under their respective licenses.\n- Fonts: system fonts only (Lucida Grande is not bundled).\n- Three.js: MIT, bundled locally.\n`;
writeFileSync(join(root, 'LICENSES.md'), md);
console.log(`LICENSES.md written for ${rows.length} packages`);
if (disallowed.length) process.exitCode = 2;
