#!/usr/bin/env node
/**
 * Generates LICENSES.md from the installed production dependencies of every workspace package.
 *
 * With no argument it writes the committed LICENSES.md. Given a path it writes there instead, which
 * is how `pnpm verify`'s `licenses-up-to-date` gate compares the committed file against a fresh
 * render without dirtying the working tree.
 */
import { readFileSync, writeFileSync, existsSync, realpathSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// fileURLToPath, not URL#pathname: the latter yields "/C:/..." on Windows and keeps %20 escapes.
const root = fileURLToPath(new URL('..', import.meta.url));
const workspaces = ['packages/contracts', 'packages/domain', 'packages/aqua-ui', 'packages/audio-core', 'packages/recommendations', 'music-player', 'docker-container', 'windows-companion', 'local-helper'];

/**
 * Node's own lookup: the nearest node_modules/<name> walking up from the requiring package. With a
 * hoisted layout a package installed at several versions keeps the extra copies nested under its
 * dependents, so resolving from the root alone would report the wrong version.
 */
function findPackageDir(name, fromDir) {
  let dir = fromDir;
  for (;;) {
    const candidate = join(dir, 'node_modules', name);
    if (existsSync(join(candidate, 'package.json'))) return realpathSync(candidate);
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

const seen = new Map(); // "name@version" -> row
const visited = new Set(); // resolved package directories, so cycles terminate
function visit(name, from, fromDir) {
  if (name.startsWith('@now-playing/')) return;
  const dir = findPackageDir(name, fromDir);
  if (!dir) {
    const key = `${name}@?`;
    if (!seen.has(key)) seen.set(key, { name, version: '?', license: 'unresolved', from });
    return;
  }
  if (visited.has(dir)) return;
  visited.add(dir);
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const license = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? (Array.isArray(pkg.licenses) ? pkg.licenses.map((l) => l.type).join(' OR ') : 'UNKNOWN');
  const key = `${name}@${pkg.version}`;
  if (!seen.has(key)) seen.set(key, { name, version: pkg.version, license, from });
  for (const dep of Object.keys(pkg.dependencies ?? {})) visit(dep, name, dir);
}
for (const ws of workspaces) {
  const wsDir = join(root, ws);
  const pkg = JSON.parse(readFileSync(join(wsDir, 'package.json'), 'utf8'));
  for (const dep of Object.keys(pkg.dependencies ?? {})) visit(dep, ws, wsDir);
}
const rows = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || String(a.version).localeCompare(String(b.version), undefined, { numeric: true }));
const counts = {};
for (const v of rows) counts[v.license] = (counts[v.license] ?? 0) + 1;
const disallowed = rows.filter((v) => /GPL(?!-.*with)|SSPL|CC-BY-NC/i.test(v.license) && !/LGPL/.test(v.license));
let md = `# Third-party licenses\n\nGenerated by \`node scripts/licenses.mjs\` from the installed production dependency graph of every workspace package (${rows.length} packages). The suite itself is MIT.\n\n## Summary\n\n| License | Packages |\n|---|---:|\n`;
for (const [l, n] of Object.entries(counts).sort((a, b) => b[1] - a[1])) md += `| ${l} | ${n} |\n`;
md += `\n${disallowed.length ? `**Attention:** ${disallowed.length} package(s) carry copyleft/non-commercial licenses: ${[...new Set(disallowed.map((v) => v.name))].join(', ')}` : 'No GPL/SSPL/non-commercial licenses are present in the production graph.'}\n\n## Packages\n\n| Package | Version | License | Pulled in by |\n|---|---|---|---|\n`;
for (const v of rows) md += `| ${v.name} | ${v.version} | ${v.license} | ${v.from} |\n`;
md += `\n## Bundled runtime notes\n\n- Docker image: Debian packages incl. FFmpeg (GPL/LGPL, invoked as a separate process, not linked).\n- Electron: MIT; Chromium/Node components under their respective licenses.\n- Fonts: system fonts only (Lucida Grande is not bundled).\n- Three.js: MIT, bundled locally.\n`;
const out = process.argv[2] ? resolve(process.argv[2]) : join(root, 'LICENSES.md');
writeFileSync(out, md);
console.log(`${out} written for ${rows.length} packages`);
if (disallowed.length) process.exitCode = 2;
